// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  standalone: false,
})
export class AppComponent {
  title = 'angular';
  imageForm = new FormGroup({
    width: new FormControl(),
    height: new FormControl(),
  });

  get width() {
    return this.imageForm.get('width')?.value || 800;
  }

  get height() {
    return this.imageForm.get('height')?.value || 600;
  }
}

<main>
  <img
    unpic
    src="https://images.unsplash.com/photo-1617718295766-0f839c2853e7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTczfHxyYWluZm9yZXN0JTIwYmVhY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60"
    layout="fullWidth"
    alt=""
    priority
    height="400"
    background="auto"
  />
  <img
    unpic
    src="https://cdn.shopify.com/static/sample-images/garnished.jpeg"
    layout="constrained"
    width="800"
    height="600"
    alt="Shopify"
  />
  <img
    unpic
    src="https://bunnyoptimizerdemo.b-cdn.net/bunny7.jpg?width=300"
    width="400"
    height="300"
    layout="fixed"
    alt="Bunny.net"
  />
  <form [formGroup]="imageForm">
    <label>
      Width:
      <input type="number" formControlName="width" />
    </label>
    <label>
      Height:
      <input type="number" formControlName="height" />
    </label>
  </form>

  <img
    unpic
    src="https://bunnyoptimizerdemo.b-cdn.net/bunny7.jpg?width=300"
    [width]="width"
    [height]="height"
  />
  <div>
    <picture class="hero">
      <!-- Large screens get a full-width hero image -->
      <source
        unpic
        src="https://images.unsplash.com/photo-1694406805270-f3a93e91f4b6"
        media="(min-width: 601px)"
        layout="fullWidth"
      />
      <!-- Small screens get a constrained square image -->
      <source
        unpic
        src="https://images.unsplash.com/photo-1693711942336-f4f9963bd364"
        media="(max-width: 600px)"
        width="600"
        height="600"
      />
      <!-- Always include an Image as the final element -->
      <img
        unpic
        src="https://images.unsplash.com/photo-1693711942336-f4f9963bd364"
        width="600"
        height="600"
        alt="Aurora"
        unstyled
      />
    </picture>
  </div>
  <style>
    /* Style for all layouts */
    .hero img {
      object-fit: cover;
      width: 100%;
    }

    @media (min-width: 601px) {
      /* Style for full-width layout */
      .hero img {
        height: 600px;
      }
    }

    @media (max-width: 600px) {
      /* Style for constrained layout */
      .hero img {
        max-width: 600px;
        aspect-ratio: 1/1;
      }
    }
  </style>
</main>

// examples/vue/app.vue
<script setup lang="ts">
import { Image, Source } from "@unpic/vue";
</script>

<template>
  <div>
    <Image
    src="https://images.unsplash.com/photo-1617718295766-0f839c2853e7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTczfHxyYWluZm9yZXN0JTIwYmVhY2h8ZW58MHx8MHx8&auto=format&fit=crop&w=900&q=60"
    layout="fullWidth"
      alt=""
      priority
      height="400"
      background="auto"
    />
    <Image
      src="https://cdn.shopify.com/static/sample-images/garnished.jpeg"
      layout="constrained"
      width="800"
      height="600"
      alt="Shopify"
    />
    <Image
      src="https://bunnyoptimizerdemo.b-cdn.net/bunny7.jpg?width=300"
      width="400"
      height="300"
      layout="fixed"
      alt="Bunny.net"
    />
    <picture class="hero">
      <!-- Large screens get a full-width hero image -->
      <Source
        src="https://images.unsplash.com/photo-1694406805270-f3a93e91f4b6"
        media="(min-width: 601px)"
        layout="fullWidth"
      />
      <!-- Small screens get a constrained square image -->
      <Source
        src="https://images.unsplash.com/photo-1693711942336-f4f9963bd364"
        media="(max-width: 600px)"
        width="600"
        height="600"
      />
      <!-- Always include an Image as the final element -->
      <Image
        src="https://images.unsplash.com/photo-1693711942336-f4f9963bd364"
        width="600"
        height="600"
        alt="Aurora"
        unstyled
      />
    </picture>
  </div>
</template>

<style scoped>
/* Style for all layouts */
.hero img {
  object-fit: cover;
  width: 100%;
}

@media (min-width: 601px) {
  /* Style for full-width layout */
  .hero img {
    height: 600px;
  }
}
@media (max-width: 600px) {
  /* Style for constrained layout */
  .hero img {
    max-width: 600px;
    aspect-ratio: 1/1;
  }
}
</style>
