// packages/react/src/base/image.tsx
import * as React from "react";
import {
  transformBaseImageProps,
  type UnpicBaseImageProps,
  type Operations,
} from "@unpic/core/base";
import { camelizeProps } from "../camelize";

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<
  TOperations,
  TOptions,
  React.ImgHTMLAttributes<HTMLImageElement>
>;

export function Image<T extends Operations, O>({
  transformer,
  ...props
}: ImageProps<T, O>) {
  const camelizedProps = camelizeProps(
    transformBaseImageProps({ transformer, ...props }),
  );
  return <img {...camelizedProps} />;
}

// packages/qwik/src/components/base/image.tsx
import { component$ } from "@builder.io/qwik";
import type { QRL, QwikIntrinsicElements } from "@builder.io/qwik";
import type { Operations, UnpicBaseImageProps } from "@unpic/core";
import { transformBaseImageProps } from "@unpic/core/base";
import type { TransformerFunction } from "unpic";
export type ImageProps<
  TOperations extends Operations,
  TOptions = unknown,
> = Omit<
  UnpicBaseImageProps<TOperations, TOptions, QwikIntrinsicElements["img"]>,
  "transformer"
> & {
  transformer$: QRL<TransformerFunction<TOperations, TOptions>>;
};

export const Image = component$(
  <TOperations extends Operations, TOptions = unknown>({
    transformer$,
    ...props
  }: ImageProps<TOperations, TOptions>) => {
    const transformer = transformer$.resolved;
    return (
      <img
        {...transformBaseImageProps<
          TOperations,
          TOptions,
          QwikIntrinsicElements["img"]
        >({ transformer, ...props } as UnpicBaseImageProps<
          TOperations,
          TOptions,
          QwikIntrinsicElements["img"]
        >)}
      />
    );
  },
);
