// packages/preact/src/image.tsx
import { transformProps, UnpicImageProps } from "@unpic/core";
import { JSX } from "preact";
import { UnSignal } from ".";

export type ImageProps = UnpicImageProps<
  UnSignal<JSX.HTMLAttributes<HTMLImageElement>>
>;

export function Image(props: ImageProps) {
  return <img {...transformProps(props)} />;
}

// packages/qwik/src/components/image.tsx
import { component$ } from "@builder.io/qwik";
import { transformProps } from "@unpic/core";
import type { QwikIntrinsicElements } from "@builder.io/qwik";
import type { UnpicImageProps } from "@unpic/core";
export type ImageProps = UnpicImageProps<QwikIntrinsicElements["img"]>;

export const Image = component$((props: ImageProps) => {
  return <img {...transformProps(props)} />;
});
