// packages/vue/src/base/source.vue
<template>
  <source v-bind="sourceProps" />
</template>

<script setup lang="ts" generic="TOperations extends Operations, TOptions">
import { transformBaseSourceProps, type UnpicBaseSourceProps, type Operations } from "@unpic/core/base";
import { SourceHTMLAttributes, computed, useAttrs } from "vue";

type SourceAttrs = /* @vue-ignore */ SourceHTMLAttributes;

const props = defineProps<UnpicBaseSourceProps<TOperations, TOptions>>();

const attrs: SourceAttrs = useAttrs();

const sourceProps = computed(() =>
  transformBaseSourceProps<SourceAttrs, TOperations, TOptions>({
    ...attrs,
    ...props,
  }),
);
</script>

// packages/preact/src/base/source.tsx
import {
  transformBaseSourceProps,
  type UnpicBaseSourceProps,
  type Operations,
} from "@unpic/core/base";
import { UnSignal } from "..";
export type { UnpicBaseSourceProps as SourceProps };
import { JSX } from "preact";

export function Source<TOperations extends Operations, TOptions>(
  props: UnpicBaseSourceProps<TOperations, TOptions>,
) {
  return (
    <source
      {...transformBaseSourceProps<
        UnSignal<JSX.SourceHTMLAttributes<HTMLSourceElement>>,
        TOperations,
        TOptions
      >(props)}
    />
  );
}
