// packages/solid/src/image.tsx
import { transformProps, UnpicImageProps } from "@unpic/core";
import { JSX } from "solid-js/jsx-runtime";

export type ImageProps = UnpicImageProps<
  JSX.ImgHTMLAttributes<HTMLImageElement>
>;
export default function Image(props: ImageProps): JSX.Element {
  return <img {...transformProps(props)} />;
}

// packages/react/src/image.tsx
import * as React from "react";
import {
  CoreImageAttributes,
  transformProps,
  UnpicImageProps,
} from "@unpic/core";

export default function Image(
  props: UnpicImageProps<
    React.ImgHTMLAttributes<HTMLImageElement>,
    React.CSSProperties
  >
) {
  return <img {...transformProps(props)} />;
}
