// packages/qwik/src/components/source.tsx
import { component$ } from "@builder.io/qwik";
import { transformSourceProps } from "@unpic/core";
import type { UnpicSourceProps } from "@unpic/core";
export type SourceProps = UnpicSourceProps;

export const Source = component$((props: SourceProps) => {
  return <source {...transformSourceProps(props)} />;
});

// packages/react/src/source.tsx
import * as React from "react";
import { transformSourceProps, UnpicSourceProps } from "@unpic/core";
export type SourceProps = UnpicSourceProps;

export const Source = React.forwardRef<HTMLSourceElement, SourceProps>(
  function Source(props, ref) {
    return <source {...transformSourceProps(props)} ref={ref} />;
  },
);
