// packages/react/src/base/image.tsx
import * as React from "react";
import {
  transformBaseImageProps,
  type UnpicBaseImageProps,
  type Operations,
} from "@unpic/core/base";
import { camelizeProps } from "../camelize";

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<
  TOperations,
  TOptions,
  React.ImgHTMLAttributes<HTMLImageElement>
>;

export function Image<T extends Operations, O>({
  transformer,
  ...props
}: ImageProps<T, O>) {
  const camelizedProps = camelizeProps(
    transformBaseImageProps({ transformer, ...props }),
  );
  return <img {...camelizedProps} />;
}

// packages/solid/src/base/image.tsx
import {
  type Operations,
  type UnpicBaseImageProps,
  transformBaseImageProps,
} from "@unpic/core/base";
import { JSX } from "solid-js/jsx-runtime";

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<
  TOperations,
  TOptions,
  JSX.ImgHTMLAttributes<HTMLImageElement>
>;
export default function Image<TOperations extends Operations, TOptions>(
  props: ImageProps<TOperations, TOptions>,
): JSX.Element {
  return <img {...transformBaseImageProps(props)} />;
}
