// packages/preact/src/base/image.tsx
import {
  transformBaseImageProps,
  type UnpicBaseImageProps,
  type Operations,
} from "@unpic/core/base";
import { JSX } from "preact";
import { UnSignal } from "../index";

type ImgPropsWithoutSignals = UnSignal<JSX.ImgHTMLAttributes<HTMLImageElement>>;

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<TOperations, TOptions, ImgPropsWithoutSignals>;

export function Image<T extends Operations, O>({
  transformer,
  ...props
}: ImageProps<T, O>) {
  return (
    <img
      {...transformBaseImageProps<
        T,
        O,
        ImgPropsWithoutSignals,
        ImgPropsWithoutSignals["style"]
      >({ transformer, ...props })}
    />
  );
}

// packages/solid/src/base/image.tsx
import {
  type Operations,
  type UnpicBaseImageProps,
  transformBaseImageProps,
} from "@unpic/core/base";
import { JSX } from "solid-js/jsx-runtime";

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<
  TOperations,
  TOptions,
  JSX.ImgHTMLAttributes<HTMLImageElement>
>;
export default function Image<TOperations extends Operations, TOptions>(
  props: ImageProps<TOperations, TOptions>,
): JSX.Element {
  return <img {...transformBaseImageProps(props)} />;
}
