// packages/preact/src/image.tsx
import { transformProps, UnpicImageProps } from "@unpic/core";
import { JSX } from "preact";
import { UnSignal } from ".";

type ImgPropsWithoutSignals = UnSignal<JSX.ImgHTMLAttributes<HTMLImageElement>>;

export type ImageProps = UnpicImageProps<ImgPropsWithoutSignals>;

export function Image(props: ImageProps) {
  return <img {...transformProps<ImgPropsWithoutSignals>(props)} />;
}

// packages/solid/src/image.tsx
import { transformProps, UnpicImageProps } from "@unpic/core";
import { JSX } from "solid-js/jsx-runtime";

export type ImageProps = UnpicImageProps<
  JSX.ImgHTMLAttributes<HTMLImageElement>
>;
export default function Image(props: ImageProps): JSX.Element {
  return <img {...transformProps(props)} />;
}
