// packages/qwik/src/components/source.tsx
import { component$ } from "@builder.io/qwik";
import { transformSourceProps } from "@unpic/core";
import type { UnpicSourceProps } from "@unpic/core";
export type SourceProps = UnpicSourceProps;

export const Source = component$((props: SourceProps) => {
  return <source {...transformSourceProps(props)} />;
});

// packages/preact/src/source.tsx
import { JSX } from "preact";
import { transformSourceProps, UnpicSourceProps } from "@unpic/core";
import { UnSignal } from "./index.js";
export type SourceProps = UnpicSourceProps;

export function Source(props: SourceProps) {
  return (
    <source
      {...transformSourceProps<
        UnSignal<JSX.SourceHTMLAttributes<HTMLSourceElement>>
      >(props)}
    />
  );
}
