// packages/vue/src/base/image.vue
<template>
  <img v-bind="imageProps" />
</template>

<script setup lang="ts" generic="TOperations extends Operations, TOptions">
import { transformBaseImageProps, type UnpicBaseImageProps, type Operations } from "@unpic/core/base";
import { ImgHTMLAttributes, computed, useAttrs } from "vue";
import type { StyleValue } from "vue";

type ImageAttrs = /* @vue-ignore */ ImgHTMLAttributes;

const props = defineProps<UnpicBaseImageProps<TOperations, TOptions, ImageAttrs>>();

const attrs: ImageAttrs = useAttrs();

const imageProps = computed(() =>
  transformBaseImageProps<TOperations, TOptions, ImageAttrs, StyleValue>({
    ...attrs,
    ...props,
  }),
);
</script>

// packages/react/src/base/image.tsx
import * as React from "react";
import {
  transformBaseImageProps,
  type UnpicBaseImageProps,
  type Operations,
} from "@unpic/core/base";
import { camelizeProps } from "../camelize";

export type ImageProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseImageProps<
  TOperations,
  TOptions,
  React.ImgHTMLAttributes<HTMLImageElement>
>;

export function Image<T extends Operations, O>({
  transformer,
  ...props
}: ImageProps<T, O>) {
  const camelizedProps = camelizeProps(
    transformBaseImageProps({ transformer, ...props }),
  );
  return <img {...camelizedProps} />;
}
