// packages/qwik/src/components/base/source.tsx
import { component$, QRL } from "@builder.io/qwik";
import type { Operations, UnpicBaseSourceProps } from "@unpic/core";
import { transformBaseSourceProps } from "@unpic/core/base";
import { TransformerFunction } from "unpic";
export type SourceProps<TOperations extends Operations, TOptions> = Omit<
  UnpicBaseSourceProps<TOperations, TOptions>,
  "transformer"
> & {
  transformer$: QRL<TransformerFunction<TOperations, TOptions>>;
};

export const Source = component$(
  <TOperations extends Operations, TOptions>({
    transformer$,
    ...props
  }: SourceProps<TOperations, TOptions>) => {
    const transformer = transformer$.resolved;
    return (
      <source
        {...transformBaseSourceProps({
          transformer,
          ...props,
        } as UnpicBaseSourceProps<TOperations, TOptions>)}
      />
    );
  },
);

// packages/react/src/base/source.tsx
import {
  transformBaseSourceProps,
  type UnpicBaseSourceProps,
  type Operations,
} from "@unpic/core/base";
import { camelizeProps } from "../camelize";
export type { UnpicBaseSourceProps as SourceProps };

export function Source<TOperations extends Operations, TOptions>(
  props: UnpicBaseSourceProps<TOperations, TOptions>,
) {
  const camelizedProps = camelizeProps(transformBaseSourceProps(props));
  return <source {...camelizedProps} />;
}
