// packages/solid/src/base/source.tsx
import {
  Operations,
  transformBaseSourceProps,
  type UnpicBaseSourceProps,
} from "@unpic/core/base";
import { JSX } from "solid-js/jsx-runtime";

export type SourceProps<
  TOperations extends Operations,
  TOptions,
> = UnpicBaseSourceProps<TOperations, TOptions>;
export default function Source<TOperations extends Operations, TOptions>(
  props: SourceProps<TOperations, TOptions>,
): JSX.Element {
  return <source {...transformBaseSourceProps(props)} />;
}

// packages/react/src/base/source.tsx
import {
  transformBaseSourceProps,
  type UnpicBaseSourceProps,
  type Operations,
} from "@unpic/core/base";
import { camelizeProps } from "../camelize";
export type { UnpicBaseSourceProps as SourceProps };

export function Source<TOperations extends Operations, TOptions>(
  props: UnpicBaseSourceProps<TOperations, TOptions>,
) {
  const camelizedProps = camelizeProps(transformBaseSourceProps(props));
  return <source {...camelizedProps} />;
}
