// packages/qwik/src/components/source.tsx
import { component$ } from "@builder.io/qwik";
import { transformSourceProps } from "@unpic/core";
import type { UnpicSourceProps } from "@unpic/core";
export type SourceProps = UnpicSourceProps;

export const Source = component$((props: SourceProps) => {
  return <source {...transformSourceProps(props)} />;
});

// packages/svelte/src/lib/source.svelte
<script lang="ts">
  import type { SourceProps as BaseSourceProps } from "./types";

  import { transformSourceProps } from "@unpic/core";

  let props: BaseSourceProps = $props();

  let transformedProps = $derived(
    transformSourceProps({
      ...props,
    }),
  );
</script>

<source {...transformedProps} />
